version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: ims_postgres
    restart: always
    environment:
      POSTGRES_USER: ims_user
      POSTGRES_PASSWORD: ims_password
      POSTGRES_DB: ims_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    container_name: ims_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ims_user
      MONGO_INITDB_ROOT_PASSWORD: ims_password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: ims_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data: